# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/demo/
Content-Type: application/json
Authorization: Token 23ae8abef7514549854e878bcfb3d6ee5a0d1d60

###

# создание объявления
POST {{baseUrl}}/demo/
Content-Type: application/json
Authorization: Token f2055f80525ecfcc22fb1b03db8545122ff5aaa2

{
  "title": "Шкаф IK",
  "description": "Счно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/demo/4/
Content-Type: application/json
Authorization: Token 7ecb993fe261108c5ad25edfdbbdf8494e8be7ae

{
  "status": "DRAFT"
}

###

# фильтрация по создателю
GET {{baseUrl}}/demo/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/demo/?created_at_before=2022-12-01
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/demo/?status=CLOSED
Content-Type: application/json

###

# фильтрация по избранным объявлениям
GET {{baseUrl}}/demo/favorite/
Content-Type: application/json
Authorization: Token 7ecb993fe261108c5ad25edfdbbdf8494e8be7ae

###

# добавление в избранное 
POST {{baseUrl}}/demo/favorite/
Content-Type: application/json
Authorization: Token 7ecb993fe261108c5ad25edfdbbdf8494e8be7ae

{
  "id": 7
}