# Generated by Django 4.1.3 on 2022-12-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_advertisement_creator_favoriteadvertisement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteadvertisement',
            name='tagged_at',
        ),
    ]
