# Generated by Django 4.1.3 on 2022-12-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_remove_favoriteadvertisement_tagged_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoriteadvertisement',
            constraint=models.UniqueConstraint(fields=('user', 'advertisement'), name='unique_favorite_ad'),
        ),
    ]
