# Generated by Django 4.1.3 on 2022-12-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_favoriteadvertisement_unique_favorite_ad'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriteadvertisement',
            name='unique_favorite_ad',
        ),
    ]
