# Generated by Django 4.1.3 on 2022-12-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_remove_favoriteadvertisement_unique_favorite_ad'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoriteadvertisement',
            constraint=models.UniqueConstraint(fields=('user', 'advertisement'), name='unique_favorite_ad'),
        ),
    ]
